name: seasonal_decor_example
description: Example app for the seasonal_decor package.
publish_to: 'none'
version: 1.1.6

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  seasonal_decor:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
